version: "3.8"

services:
  discord-stream-bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: discord-stream-bot:latest
    container_name: discord-stream-bot
    restart: unless-stopped

    # Resource limits for better performance
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 4G
        reservations:
          cpus: "2.0"
          memory: 2G

    # Environment variables
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=3072
      - FFMPEG_THREADS=4
      # Enable FFmpeg hardware acceleration if available
      - LIBVA_DRIVER_NAME=iHD
      - LIBVA_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri

    # Volume mounts
    volumes:
      - ./config.json:/app/config.json:ro
      - ./logs:/app/logs
      # Mount for hardware acceleration (optional)
      - /dev/dri:/dev/dri

    # Network configuration
    network_mode: bridge

    # Security options
    security_opt:
      - no-new-privileges:true

    # User configuration (non-root)
    user: "1001:1001"

    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

    # Additional runtime configurations
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1

    # Enable shared memory for better FFmpeg performance
    shm_size: "2gb"

    # Labels for better organization
    labels:
      - "com.discord-stream-bot.name=Discord Stream Bot"
      - "com.discord-stream-bot.version=1.0.0"
      - "com.discord-stream-bot.description=Discord video streaming bot with FFmpeg"
