version: "3.8"

services:
  discord-stream-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-video-stream-bot
    restart: unless-stopped

    # Mount config file from host
    volumes:
      - ./config.json:/app/config.json:ro
      - ./logs:/app/logs

    # Environment variables (optional, config.json takes precedence)
    environment:
      - NODE_ENV=production
      - TZ=UTC

    # Resource limits for performance
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "2.0"
        reservations:
          memory: 1G
          cpus: "1.0"

    # Logging configuration
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    # Network configuration (optional)
    networks:
      - discord-bot-network

networks:
  discord-bot-network:
    driver: bridge
